### ISSUE TITLE
Initial research of GCP features

### ISSUE THREAD

**Issue by edwardlach** [PSU-CMPSC-445/python-ml#14]
- Google Cloud Bucket (storing images?)

- Google Functions (possibly running ML model?)

- Cloud Run (For running react app?)

**Comment by setalias** [comment]
Liz & Sandy working on this. Week 1

**Comment by ElizabethKelly5496** [comment]
We will need someone to create a GCP project that is associated with their GPC account. They should then grant the rest of the team access to that project. All GCP resources we use will be associated with that GCP project.

We can either train the model using Colab, or train the model directly using GCP's AI Platform. In either case we will need to create a GCP Cloud Storage Bucket. 

Tutorial on AI Platform running keras and Tensorflow: 
https://cloud.google.com/ai-platform/docs/getting-started-keras

Training a model with Colab and deploying to a cloud storage bucket:
https://towardsdatascience.com/develop-train-and-deploy-tensorflow-models-using-google-cloud-ai-platform-32b47095878b

For our React web app, we should use GCP's App Engine: 
https://medium.com/@masitano.sichone/creating-a-react-app-on-google-app-engine-de03f3721710
