### ISSUE TITLE
Create Web App

### ISSUE THREAD

**Issue by edwardlach** [PSU-CMPSC-445/python-ml#22]
![Initial Load Screen](https://images.zenhubusercontent.com/5dd6dbbfa176990001ece198/4b8763c1-344d-4b72-b30f-7dd24c57cbeb)
![Identified Part Screen](https://images.zenhubusercontent.com/5dd6dbbfa176990001ece198/fc46bc56-f49a-4310-b8bd-a26e067f7c46)

**Comment by Ramy-Huffman** [comment]
Complete Web App with model exported from GCP.
