### ISSUE TITLE
Random Image Rotation Pipeline

### ISSUE THREAD

**Issue by edwardlach** [PSU-CMPSC-445/python-ml#24]
We need to create an image processing pipeline that will take each of our captured real world images of Lego and randomly rotate and adjust the placement of the part in the image.  This will enlarge our sample set of real world photos which should improve our model.  An article on the process can be found below:

[Why and How to Implement Random Rotate Data Augmentation](https://blog.roboflow.com/why-and-how-to-implement-random-rotate-data-augmentation/)

**Comment by setalias** [comment]
Complete. Likely will not be used.
